services:
  pgs:
    image: postgres:9.4
    restart: always
    ports:
      - ${PGS_PORT:-5432}:5432
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ocdb-data:/var/lib/postgresql/data
    networks:
      - mynetwork

  openclinica:
    image: piegsaj/openclinica:oc-3.13
    restart: always
    ports:
      - ${OC_PORT:-8080}:8080
    environment:
      LOG_LEVEL: ${LOG_LEVEL}
      TZ: ${TZ}
      DB_TYPE: ${DB_TYPE}
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      DB_PORT: ${DB_PORT}
      SUPPORT_URL: ${SUPPORT_URL}
    depends_on:
      - pgs
    volumes:
      - oc-data:/usr/local/tomcat/openclinica.data
    networks:
      - mynetwork

volumes:
  ocdb-data:
  oc-data:

networks:
  mynetwork:
    driver: bridge